<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAP00395" failures="1" tests="1" name="Default test" time="10.937" errors="0" timestamp="2024-02-27T16:57:34 IST">
  <testcase classname="com.cztffa.page.personalinfo.PersonalInfoPageTest" name="invalidSSNScenario" time="4.019">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.cztffa.objects.ProductTab.getProducts()&amp;quot; because &amp;quot;productTab&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.cztffa.objects.ProductTab.getProducts()" because "productTab" is null
at com.cztffa.page.product.ProductSelectorPage.basicProductSelectionPage(ProductSelectorPage.java:81)
at com.cztffa.page.product.ProductSelectorPage.getStarted(ProductSelectorPage.java:23)
at com.cztffa.page.personalinfo.PersonalInfoPage.fillPersonDetails(PersonalInfoPage.java:189)
at com.cztffa.page.personalinfo.PersonalInfoPageTest.invalidSSNScenario(PersonalInfoPageTest.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- invalidSSNScenario -->
  <testcase classname="com.cztffa.page.personalinfo.PersonalInfoPageTest" name="validateSecurityWord" time="0.0">
    <ignored/>
  </testcase> <!-- validateSecurityWord -->
  <testcase classname="com.cztffa.page.personalinfo.PersonalInfoPageTest" name="saveResumePersonalInfo" time="0.0">
    <ignored/>
  </testcase> <!-- saveResumePersonalInfo -->
</testsuite> <!-- Default test -->
